[workspace]
members = [
  "contracts/*",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["kromsten <kromsten@pm.me>"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
